### ISSUE TITLE
Melhoria do Corpus

### ISSUE THREAD

**Issue by oliveiracwb** [Edresson/TTS-Portuguese-Corpus#2]
Ausentes em texts.csv:
sample-1204.wav
sample-1269.wav
sample-1527.wav
sample-3558.wav
sample-5428.wav
sample-6397.wav

Duplicados em texts.csv:
sample-1430.wav
sample-47.wav
sample-70.wav

A seguir uma lista de arquivos em que encontrei erros de fonética ou pronuncia ou ainda palavras inteiras trocadas:
> sample-1000 - Erro fonético em "Patriotas"
> sample-1004 - ..  "derrotar"
> sample-1006 -  "Vêneto"
> sample-1008 -  "Terra"
> sample-1013 -  "contrastando"
> sample-1015 -  "é" e "Cel" (Coronel) - implementar um cleaner ?
> sample-1022 -  "honorario"
> sample-1024 -  "vinte e quatro"  / "vinte e oito de junho"
> sample-1026 -  "difícil" (lido como fácil)
> sample-1027 -  "barreiras"
> sample-1029 - Não lido "PNUD"
> sample-102 -  "cruzavam" para "cruzaram"
> sample-1031-  "adutos" para "adultos"
> sample-1032- Estrangerismo "singles"
> sample-1052: Erro fonético em "escacez"
> sample-1053: "hesitação" lido como "exitação"
> sample-1058: Frase troca leitura das datas
> sample-1071: Junho por Julho
> sample-108: O texto difere parcialmente da frase lida
> sample-1098: monoxilos
> sample-110: Erro na leitura dos números (possui a palavra "pontos" não lida)

Com os dias vou atualizando a lista.

**Comment by Edresson** [comment]
Thanks :)
