### ISSUE TITLE
Alternative Training Platform/Language

### ISSUE THREAD

**Issue by Tele582** [Edresson/TTS-Portuguese-Corpus#3]
Thanks for your awesome work.

Please how do I train this for another language on a PC with no GPU. Can I use colab notebook?

What do you suggest? I've been studying your work for a while.

**Comment by Edresson** [comment]
Hi,
My dataset is for Brazilian Portuguese. To train in another language you need to download or create your corpus.

My best experiments use Mozilla TTS: https://github.com/mozilla/TTS

Read the FAQ: https://github.com/mozilla/TTS/wiki/FAQ

You can ask for help at the Discourse Forums: https://discourse.mozilla.org/c/tts/285
