### ISSUE TITLE
bit.do links don't work

### ISSUE THREAD

**Issue by samialsindi** [Edresson/TTS-Portuguese-Corpus#4]
Hi, really interested to see your work.
When I try to open any of the bit.do links I get a 'bit.do’s server IP address could not be found.' error.
Could you please update the Colab links?
Thanks in advance.

**Comment by Edresson** [comment]
Hi, 
I updated the links :)

**Comment by samialsindi** [comment]
You are a legend! Thanks

**Comment by Edresson** [comment]
Currently on Mozilla TTS we have better models. Maybe to get a better result you can train a new model with this dataset :). In addition, we have the new WaveGrad (https://github.com/mozilla/TTS/issues/518) vocoder that allows high quality synthesis.

**Comment by samialsindi** [comment]
Awesome, will check it out!
