### ISSUE TITLE
Dá para usar como fala para texto?

### ISSUE THREAD

**Issue by CrashAngelArts** [Edresson/TTS-Portuguese-Corpus#5]
Amigo, dá para eu usar esses arquivos em algum software para criar um programa em python que funcione de maneira offline de fala para texto ?

**Comment by Edresson** [comment]
Olá modelos de reconhecimento automático de fala são geralmente treinados utilizando muitos locutores e esse dataset possui apenas um único locutor. Caso esteja interessado em reconhecimento automatico de fala você pode olhar os modelos open source disponiveis no huggingface como esse: https://huggingface.co/lgris/wav2vec2-large-xlsr-open-brazilian-portuguese
