### ISSUE TITLE
Adaptação para outras vozes

### ISSUE THREAD

**Issue by ricardohalla** [Edresson/TTS-Portuguese-Corpus#6]
É possível usar esse banco de dados para treinar um modelo de TTS que sintetize vozes de outras pessoas a partir de uma pequena quantidade de samples? Ou para cada voz em particular eu vou precisar produzir um banco de dados dessa voz?

Por exemplo: caso eu queira sintetizar minha voz, eu vou precisar de um banco de dados gigante da minha voz? Ou é possível usar algum método que sintetize a minha voz a partir de um treinamento com um banco de dados já existente (como esse por exemplo) de outras pessoas? Há algo na literatura a respeito disso?

Agradeço desde já!

**Comment by Edresson** [comment]
Você pode sim utilizar esse dataset para fazer transfer learning e aprender outras vozes. Porém atualmente para adaptar para uma nova voz você vai precisar algo em torno de 1 hora de fala. 

Atenciosamente,
Edresson Casanova.
